name: Xcode - Build and Release

on: workflow_dispatch
  # push:
  #   tags:
      # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and release with xcodebuild
    runs-on: macos-13

    steps:  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check xcodebuild version
        run: xcodebuild -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -showsdks
      - name: Show buildable schemes
        run: xcodebuild -list
      - uses: mxcl/xcodebuild@v1.9.2
        with:
          platform: macOS
          action: build
          verbosity: xcpretty
          upload-logs: always          
