name: Build and Release

on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10       

jobs:
  build:
    name: Build and release with xcodebuild
    runs-on: macos-13
    steps:
    - name: Check xcodebuild version
      run: xcodebuild -version
      
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
 
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Show buildable schemes
      run: xcodebuild -list    
     
    - name: Build App
      run: xcodebuild build -project 'Caffeinate.xcodeproj' -scheme 'Caffeinate' -destination 'generic/platform=macOS' -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Archive App
      run:  xcodebuild -scheme 'Caffeinate' -configuration Release archive -archivePath CT.xcarchive
    
    - name: Export App
      run: xcodebuild -exportArchive -exportPath . -archivePath CT.xcarchive/ -exportOptionsPlist Caffeinate/exportOptions.plist

    - name: Compress App
      run: zip -r Caffeinate.zip Caffeinate.app

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref }}
        draft: true
        files: Caffeinate.zip
